
version: 2

project_name: go-lakekeeper

builds:
  - id: lkctl
    main: ./cmd
    binary: lkctl-{{ .Os }}-{{ .Arch }}
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    ldflags:
      - -X github.com/baptistegh/go-lakekeeper/pkg/version.version={{ .Version }}
      - -X github.com/baptistegh/go-lakekeeper/pkg/version.buildDate={{ .Date }}
      - -X github.com/baptistegh/go-lakekeeper/pkg/version.gitCommit={{ .FullCommit }}
      - -X github.com/baptistegh/go-lakekeeper/pkg/version.gitTag={{ .Tag }}
      - -X github.com/baptistegh/go-lakekeeper/pkg/version.gitTreeState={{ .Env.GIT_TREE_STATE }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    ids:
      - lkctl
    name_template: |-
      lkctl-{{ .Os }}-{{ .Arch }}
    formats: [ binary ]

checksum:
  name_template: 'checksums.txt'

signs:
  - artifacts: checksum

dockers:
  - image_templates:
      - "ghcr.io/baptistegh/lkctl:v{{ .Version }}-amd64"
      - "ghcr.io/baptistegh/lkctl:v{{ .Major }}-amd64"
      - "ghcr.io/baptistegh/lkctl:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/baptistegh/lkctl:latest-amd64"
    dockerfile: docker/bin.Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/baptistegh/lkctl:v{{ .Version }}-arm64"
      - "ghcr.io/baptistegh/lkctl:v{{ .Major }}-arm64"
      - "ghcr.io/baptistegh/lkctl:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/baptistegh/lkctl:latest-arm64"
    dockerfile: docker/bin.Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/baptistegh/lkctl:{{ .Tag }}"
    image_templates:
      - "ghcr.io/baptistegh/lkctl:{{ .Tag }}-arm64"
      - "ghcr.io/baptistegh/lkctl:{{ .Tag }}-amd64"
  - name_template: "ghcr.io/baptistegh/lkctl:latest"
    image_templates:
      - "ghcr.io/baptistegh/lkctl:latest-amd64"
      - "ghcr.io/baptistegh/lkctl:latest-arm64"

release:
  github:
    owner: baptistegh
    name: go-lakekeeper

snapshot:
  version_template: "{{ incpatch .Version }}-devel"

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json