
version: 2

project_name: go-lakekeeper

builds:
  - id: lkctl
    main: ./cmd
    binary: lkctl-{{ .Os }}-{{ .Arch }}
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    ldflags:
      - -X github.com/baptistegh/go-lakekeeper/pkg/version.version={{ .Version }}
      - -X github.com/baptistegh/go-lakekeeper/pkg/version.buildDate={{ .Date }}
      - -X github.com/baptistegh/go-lakekeeper/pkg/version.gitCommit={{ .FullCommit }}
      - -X github.com/baptistegh/go-lakekeeper/pkg/version.gitTag={{ .Tag }}
      - -X github.com/baptistegh/go-lakekeeper/pkg/version.gitTreeState={{ .Env.GIT_TREE_STATE }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    name_template: |-
      lkctl-{{ .Os }}-{{ .Arch }}
    formats: ["tar.gz"]

checksum:
  name_template: 'checksums.txt'

signs:
  - artifacts: checksum

dockers_v2:
  - images:
      - ghcr.io/baptistegh/lkctl
    tags:
      - latest
      - v{{ .Version }}
      - v{{ .Major }}
      - v{{ .Major }}.{{ .Minor }}
    dockerfile: docker/bin.Dockerfile
    labels:
      "org.opencontainers.image.description": "Go Lakekeeper CLI"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.authors": "baptiste.gouhoury@scalend.fr"
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: "false"

release:
  github:
    owner: baptistegh
    name: go-lakekeeper

snapshot:
  version_template: "{{ incpatch .Version }}-devel"

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json