name: Release-Please

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/release-please.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
          config-file: release-please/release-please-config.json
          manifest-file: release-please/.release-please-manifest.json
